"""Copy a reviewed, secret-free workspace snapshot into the target Git checkout."""
from pathlib import Path
from datetime import datetime,timezone,timedelta
import os,hashlib,json,re,shutil,zipfile
source=Path('/mnt/Space1/FlowEvo+BoT');target=Path('/mnt/Space1/Flowevo-Bot-upload')
skip_dirs={'.git','.venv','venv','.wheelcheck','__pycache__','.pytest_cache','.mypy_cache','.ruff_cache'}
secret=(source/'miyao.txt').read_bytes().strip();exclusions=[];entries=[]
secret_pattern=re.compile(rb'(?:gh[pousr]_[A-Za-z0-9]{30,}|github_pat_[A-Za-z0-9_]{40,}|-----BEGIN (?:RSA |OPENSSH )?PRIVATE KEY-----|sk-[A-Za-z0-9_-]{28,})')
def check(data,path):
 if secret and secret in data:raise RuntimeError('Credential detected in '+str(path))
 if secret_pattern.search(data):raise RuntimeError('Potential secret pattern detected in '+str(path))
for base,dirs,files in os.walk(source):
 for d in list(dirs):
  p=Path(base)/d
  if d in skip_dirs or p.is_symlink():
   dirs.remove(d);exclusions.append({'path':str(p.relative_to(source)),'kind':'directory','reason':'Git internals/local environment/cache or symlink'})
 for name in files:
  path=Path(base)/name;relative=path.relative_to(source)
  if name in ('UPLOAD_MANIFEST.json','UPLOAD_EXCLUSIONS.json'):continue
  if name=='miyao.txt' or name=='.env' or (name.startswith('.env.') and name!='.env.example') or path.suffix in ('.pem','.key','.pyc','.pyo') or path.is_symlink():
   exclusions.append({'path':str(relative),'kind':'file','reason':'secret/local generated bytecode or symlink'});continue
  data=path.read_bytes();check(data,relative)
  if path.suffix in ('.zip','.whl'):
   with zipfile.ZipFile(path) as z:
    for member in z.infolist():
     if not member.is_dir():check(z.read(member),str(relative)+'!'+member.filename)
  if len(data)>=100*1024**2:raise RuntimeError('GitHub file-size limit: '+str(relative))
  destination=target/relative;destination.parent.mkdir(parents=True,exist_ok=True)
  if not destination.exists() or hashlib.sha256(destination.read_bytes()).digest()!=hashlib.sha256(data).digest():
   shutil.copy2(path,destination)
  entries.append({'path':str(relative),'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest()})
manifest={'snapshot_time':datetime.now(timezone(timedelta(hours=8),'Asia/Shanghai')).isoformat(),
 'source_workspace':str(source),'destination_repository':'https://github.com/ChenKaichen-SCUT/Flowevo-Bot',
 'scope':'entire workspace: three source projects, datasets, historical experiment records, diagnostic reports/scripts and deliverables',
 'files':sorted(entries,key=lambda x:x['path']),'file_count':len(entries),'total_bytes':sum(x['bytes'] for x in entries),
 'sensitive_data_scan':'exact runtime credential + common token/private-key patterns + archive contents; no matches',
 'nested_git_directories_included':False,'datasets_and_historical_results_included':True}
for name,data in [('UPLOAD_MANIFEST.json',manifest),('UPLOAD_EXCLUSIONS.json',{'items':exclusions,'excluded_count':len(exclusions),'note':'Credentials, virtual environments, caches and Git internals were not published. Source, datasets and requested research records were included.'})]:
 text=json.dumps(data,ensure_ascii=False,indent=2)+'\n'
 (source/name).write_text(text);(target/name).write_text(text)
print(json.dumps({'files':manifest['file_count'],'bytes':manifest['total_bytes'],'excluded_entries':len(exclusions)},ensure_ascii=False))
